### ISSUE TITLE
Using argparse for handling command line arguments.

### ISSUE THREAD

**Issue by Goofygiraffe06** [IonelPopJara/vumz#20]
Switching to argparse makes handling command-line arguments way easier and cleaner. Instead of writing a bunch of manual checks for each option, you just define them all in one place, and it takes care of generating help messages and error handling for you. This means less clutter in your code and more focus on what really matters. Plus, it makes it super user-friendly, so anyone using your program gets clear feedback if they mess up their inputs.

[](https://www.gnu.org/software/libc/manual/html_node/Argp.html) and it is a standard in all GNU projects so you know it's good.

You can assign me this issue and i am from Hacktoberfest

Thanks,
Goofygiraffe06

**Comment by IonelPopJara** [comment]
Hello! Thanks for the suggestion. It's always good to know more about GNU standards. I'll assign you to the issue then!
